pipeline{
    tools{
        maven 'mymaven'
    }
    agent any
    stages{
        stage('clone repo'){
            steps{
                git 'https://github.com/cloud99outlook/SLProject1.git'
            }
        }
        stage('build the code'){
            steps{
                sh 'mvn clean install package'
                
            }
        }
        stage('build image'){
            steps{
                sh 'cp /var/lib/jenkins/workspace/CICDPipeline/target/my-app-1.0-SNAPSHOT.jar .'
                sh 'docker build -t imageproj .'
                
            }
        }

	stage('deplaoy application'){
            steps{
                sh 'docker run -d -P imageproj'
                               
            }
        }
        
        
    }
    
}
